server:
  port: 9010

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wgxm?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  #配置http请求 文件上传 的文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itjn.entity
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    # 开启mp的日志（输出到控制台）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO

wgxm:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    userSecretKey: eyJpdiI6IlB4WlhLQ0ZqVlJtYlFvT0RnTjNnUT09
    # 设置jwt过期时间(对应的是2小时的过期时间)
    userTtl: 7200000
    # 设置前端传递过来的令牌名称
    userTokenName: authentication

    # 设置jwt签名加密时使用的秘钥
    adminSecretKey: wgxm
    # 设置jwt过期时间
    adminTtl: 7200000
    # 设置前端传递过来的令牌名称
    adminTokenName: token

logging:
  level:
    com.itjn: DEBUG  # Info
  file:
    path: log/wgxm.log
  pattern:
    dateformat: HH:mm:ss:SSS

#文件路径
files:
  path: D:/idea.code/wgxm/files/

sy:
  chat:
    api-key: 'YBHTRrFtcl0aJOFBPDgpebYwxXWcJGRUplm1PVMeCULc'
    base-url: 'https://ollama.yamazing.cn/v1/chat/completions'
    model: 'llama3-8b-8192'
    max-tokens: 4096
    stream: false

