server:
  port: 9010

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wgxm?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  #配置http请求 文件上传 的文件大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itjn.entity
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

wgxm:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    userSecretKey: eyJpdiI6IlB4WlhLQ0ZqVlJtYlFvT0RnTjNnUT09
    # 设置jwt过期时间(对应的是2小时的过期时间)
    userTtl: 7200000
    # 设置前端传递过来的令牌名称
    userTokenName: authentication

    # 设置jwt签名加密时使用的秘钥
    adminSecretKey: wgxm
    # 设置jwt过期时间
    adminTtl: 7200000
    # 设置前端传递过来的令牌名称
    adminTokenName: token

logging:
  level:
    com:
      itjn:
        mapper: debug
        service: info
        controller: info
